/* start module: os */
$pyjs['loaded_modules']['os'] = function (__mod_name__) {
	if($pyjs['loaded_modules']['os']['__was_initialized__']) return $pyjs['loaded_modules']['os'];
	var $m = $pyjs['loaded_modules']['os'];
	$m['__repr__'] = function() { return '<module: os>'; };
	$m['__was_initialized__'] = true;
	if ((__mod_name__ === null) || (typeof __mod_name__ == 'undefined')) __mod_name__ = 'os';
	$m['__name__'] = __mod_name__;
	$m.__track_lines__ = new Array();
	$m.__track_lines__[1] = "os.py, line 1:\n    # Pyjs replacement of Python's os module";
	$m.__track_lines__[4] = 'os.py, line 4:\n    import path';
	$m.__track_lines__[5] = 'os.py, line 5:\n    from os.path import (walk, curdir, pardir, sep, pathsep, defpath, extsep, altsep, devnull)';
	$m.__track_lines__[7] = "os.py, line 7:\n    name = 'pyjs'";
	$m.__track_lines__[10] = 'os.py, line 10:\n    SEEK_SET = 0';
	$m.__track_lines__[11] = 'os.py, line 11:\n    SEEK_CUR = 1';
	$m.__track_lines__[12] = 'os.py, line 12:\n    SEEK_END = 2';
	$m.__track_lines__[13] = 'os.py, line 13:\n    EX_CANTCREAT = 73';
	$m.__track_lines__[14] = 'os.py, line 14:\n    EX_CONFIG = 78';
	$m.__track_lines__[15] = 'os.py, line 15:\n    EX_DATAERR = 65';
	$m.__track_lines__[16] = 'os.py, line 16:\n    EX_IOERR = 74';
	$m.__track_lines__[17] = 'os.py, line 17:\n    EX_NOHOST = 68';
	$m.__track_lines__[18] = 'os.py, line 18:\n    EX_NOINPUT = 66';
	$m.__track_lines__[19] = 'os.py, line 19:\n    EX_NOPERM = 77';
	$m.__track_lines__[20] = 'os.py, line 20:\n    EX_NOUSER = 67';
	$m.__track_lines__[21] = 'os.py, line 21:\n    EX_OK = 0';
	$m.__track_lines__[22] = 'os.py, line 22:\n    EX_OSERR = 71';
	$m.__track_lines__[23] = 'os.py, line 23:\n    EX_OSFILE = 72';
	$m.__track_lines__[24] = 'os.py, line 24:\n    EX_PROTOCOL = 76';
	$m.__track_lines__[25] = 'os.py, line 25:\n    EX_SOFTWARE = 70';
	$m.__track_lines__[26] = 'os.py, line 26:\n    EX_TEMPFAIL = 75';
	$m.__track_lines__[27] = 'os.py, line 27:\n    EX_UNAVAILABLE = 69';
	$m.__track_lines__[28] = 'os.py, line 28:\n    EX_USAGE = 64';
	$m.__track_lines__[29] = 'os.py, line 29:\n    F_OK = 0';
	$m.__track_lines__[30] = 'os.py, line 30:\n    NGROUPS_MAX = 65536';
	$m.__track_lines__[31] = 'os.py, line 31:\n    O_APPEND = 1024';
	$m.__track_lines__[32] = 'os.py, line 32:\n    O_ASYNC = 8192';
	$m.__track_lines__[33] = 'os.py, line 33:\n    O_CREAT = 64';
	$m.__track_lines__[34] = 'os.py, line 34:\n    O_DIRECT = 16384';
	$m.__track_lines__[35] = 'os.py, line 35:\n    O_DIRECTORY = 65536';
	$m.__track_lines__[36] = 'os.py, line 36:\n    O_DSYNC = 4096';
	$m.__track_lines__[37] = 'os.py, line 37:\n    O_EXCL = 128';
	$m.__track_lines__[38] = 'os.py, line 38:\n    O_LARGEFILE = 32768';
	$m.__track_lines__[39] = 'os.py, line 39:\n    O_NDELAY = 2048';
	$m.__track_lines__[40] = 'os.py, line 40:\n    O_NOATIME = 262144';
	$m.__track_lines__[41] = 'os.py, line 41:\n    O_NOCTTY = 256';
	$m.__track_lines__[42] = 'os.py, line 42:\n    O_NOFOLLOW = 131072';
	$m.__track_lines__[43] = 'os.py, line 43:\n    O_NONBLOCK = 2048';
	$m.__track_lines__[44] = 'os.py, line 44:\n    O_RDONLY = 0';
	$m.__track_lines__[45] = 'os.py, line 45:\n    O_RDWR = 2';
	$m.__track_lines__[46] = 'os.py, line 46:\n    O_RSYNC = 1052672';
	$m.__track_lines__[47] = 'os.py, line 47:\n    O_SYNC = 1052672';
	$m.__track_lines__[48] = 'os.py, line 48:\n    O_TRUNC = 512';
	$m.__track_lines__[49] = 'os.py, line 49:\n    O_WRONLY = 1';
	$m.__track_lines__[50] = 'os.py, line 50:\n    R_OK = 4';
	$m.__track_lines__[51] = 'os.py, line 51:\n    TMP_MAX = 238328';
	$m.__track_lines__[52] = 'os.py, line 52:\n    WCONTINUED = 8';
	$m.__track_lines__[53] = 'os.py, line 53:\n    WNOHANG = 1';
	$m.__track_lines__[54] = 'os.py, line 54:\n    WUNTRACED = 2';
	$m.__track_lines__[55] = 'os.py, line 55:\n    W_OK = 2';
	$m.__track_lines__[56] = 'os.py, line 56:\n    X_OK = 1';
	$m.__track_lines__[58] = 'os.py, line 58:\n    environ = {}';
	$m.__track_lines__[60] = 'os.py, line 60:\n    def urandom(n):';
	$m.__track_lines__[74] = 'os.py, line 74:\n    raise NotImplementedError("/dev/urandom (or equivalent) not found")';
	$m.__track_lines__[75] = 'os.py, line 75:\n    return bs';
	$m.__track_lines__[77] = 'os.py, line 77:\n    def unlink(*args):';
	$m.__track_lines__[78] = 'os.py, line 78:\n    raise NotImplementedError("PyJS does not support filesystem access")';


	$pyjs['track']['module']='os';
	$pyjs['track']['lineno']=1;
	$pyjs['track']['lineno']=4;
	$pyjs['track']={'module':$pyjs['track']['module'],'lineno':$pyjs['track']['lineno']};$pyjs['trackstack']['push']($pyjs['track']);
	$m['path'] = $p['___import___']('path', 'os');
	$pyjs['trackstack']['pop']();$pyjs['track']=$pyjs['trackstack']['pop']();$pyjs['trackstack']['push']($pyjs['track']);
	$pyjs['track']['lineno']=5;
	$pyjs['track']={'module':$pyjs['track']['module'],'lineno':$pyjs['track']['lineno']};$pyjs['trackstack']['push']($pyjs['track']);
	$m['walk'] = $p['___import___']('os.path.walk', 'os', null, false);
	$pyjs['trackstack']['pop']();$pyjs['track']=$pyjs['trackstack']['pop']();$pyjs['trackstack']['push']($pyjs['track']);
	$pyjs['track']={'module':$pyjs['track']['module'],'lineno':$pyjs['track']['lineno']};$pyjs['trackstack']['push']($pyjs['track']);
	$m['curdir'] = $p['___import___']('os.path.curdir', 'os', null, false);
	$pyjs['trackstack']['pop']();$pyjs['track']=$pyjs['trackstack']['pop']();$pyjs['trackstack']['push']($pyjs['track']);
	$pyjs['track']={'module':$pyjs['track']['module'],'lineno':$pyjs['track']['lineno']};$pyjs['trackstack']['push']($pyjs['track']);
	$m['pardir'] = $p['___import___']('os.path.pardir', 'os', null, false);
	$pyjs['trackstack']['pop']();$pyjs['track']=$pyjs['trackstack']['pop']();$pyjs['trackstack']['push']($pyjs['track']);
	$pyjs['track']={'module':$pyjs['track']['module'],'lineno':$pyjs['track']['lineno']};$pyjs['trackstack']['push']($pyjs['track']);
	$m['sep'] = $p['___import___']('os.path.sep', 'os', null, false);
	$pyjs['trackstack']['pop']();$pyjs['track']=$pyjs['trackstack']['pop']();$pyjs['trackstack']['push']($pyjs['track']);
	$pyjs['track']={'module':$pyjs['track']['module'],'lineno':$pyjs['track']['lineno']};$pyjs['trackstack']['push']($pyjs['track']);
	$m['pathsep'] = $p['___import___']('os.path.pathsep', 'os', null, false);
	$pyjs['trackstack']['pop']();$pyjs['track']=$pyjs['trackstack']['pop']();$pyjs['trackstack']['push']($pyjs['track']);
	$pyjs['track']={'module':$pyjs['track']['module'],'lineno':$pyjs['track']['lineno']};$pyjs['trackstack']['push']($pyjs['track']);
	$m['defpath'] = $p['___import___']('os.path.defpath', 'os', null, false);
	$pyjs['trackstack']['pop']();$pyjs['track']=$pyjs['trackstack']['pop']();$pyjs['trackstack']['push']($pyjs['track']);
	$pyjs['track']={'module':$pyjs['track']['module'],'lineno':$pyjs['track']['lineno']};$pyjs['trackstack']['push']($pyjs['track']);
	$m['extsep'] = $p['___import___']('os.path.extsep', 'os', null, false);
	$pyjs['trackstack']['pop']();$pyjs['track']=$pyjs['trackstack']['pop']();$pyjs['trackstack']['push']($pyjs['track']);
	$pyjs['track']={'module':$pyjs['track']['module'],'lineno':$pyjs['track']['lineno']};$pyjs['trackstack']['push']($pyjs['track']);
	$m['altsep'] = $p['___import___']('os.path.altsep', 'os', null, false);
	$pyjs['trackstack']['pop']();$pyjs['track']=$pyjs['trackstack']['pop']();$pyjs['trackstack']['push']($pyjs['track']);
	$pyjs['track']={'module':$pyjs['track']['module'],'lineno':$pyjs['track']['lineno']};$pyjs['trackstack']['push']($pyjs['track']);
	$m['devnull'] = $p['___import___']('os.path.devnull', 'os', null, false);
	$pyjs['trackstack']['pop']();$pyjs['track']=$pyjs['trackstack']['pop']();$pyjs['trackstack']['push']($pyjs['track']);
	$pyjs['track']['lineno']=7;
	$m['$$name'] = 'pyjs';
	$pyjs['track']['lineno']=10;
	$m['SEEK_SET'] = 0;
	$pyjs['track']['lineno']=11;
	$m['SEEK_CUR'] = 1;
	$pyjs['track']['lineno']=12;
	$m['SEEK_END'] = 2;
	$pyjs['track']['lineno']=13;
	$m['EX_CANTCREAT'] = 73;
	$pyjs['track']['lineno']=14;
	$m['EX_CONFIG'] = 78;
	$pyjs['track']['lineno']=15;
	$m['EX_DATAERR'] = 65;
	$pyjs['track']['lineno']=16;
	$m['EX_IOERR'] = 74;
	$pyjs['track']['lineno']=17;
	$m['EX_NOHOST'] = 68;
	$pyjs['track']['lineno']=18;
	$m['EX_NOINPUT'] = 66;
	$pyjs['track']['lineno']=19;
	$m['EX_NOPERM'] = 77;
	$pyjs['track']['lineno']=20;
	$m['EX_NOUSER'] = 67;
	$pyjs['track']['lineno']=21;
	$m['EX_OK'] = 0;
	$pyjs['track']['lineno']=22;
	$m['EX_OSERR'] = 71;
	$pyjs['track']['lineno']=23;
	$m['EX_OSFILE'] = 72;
	$pyjs['track']['lineno']=24;
	$m['EX_PROTOCOL'] = 76;
	$pyjs['track']['lineno']=25;
	$m['EX_SOFTWARE'] = 70;
	$pyjs['track']['lineno']=26;
	$m['EX_TEMPFAIL'] = 75;
	$pyjs['track']['lineno']=27;
	$m['EX_UNAVAILABLE'] = 69;
	$pyjs['track']['lineno']=28;
	$m['EX_USAGE'] = 64;
	$pyjs['track']['lineno']=29;
	$m['F_OK'] = 0;
	$pyjs['track']['lineno']=30;
	$m['NGROUPS_MAX'] = 65536;
	$pyjs['track']['lineno']=31;
	$m['O_APPEND'] = 1024;
	$pyjs['track']['lineno']=32;
	$m['O_ASYNC'] = 8192;
	$pyjs['track']['lineno']=33;
	$m['O_CREAT'] = 64;
	$pyjs['track']['lineno']=34;
	$m['O_DIRECT'] = 16384;
	$pyjs['track']['lineno']=35;
	$m['O_DIRECTORY'] = 65536;
	$pyjs['track']['lineno']=36;
	$m['O_DSYNC'] = 4096;
	$pyjs['track']['lineno']=37;
	$m['O_EXCL'] = 128;
	$pyjs['track']['lineno']=38;
	$m['O_LARGEFILE'] = 32768;
	$pyjs['track']['lineno']=39;
	$m['O_NDELAY'] = 2048;
	$pyjs['track']['lineno']=40;
	$m['O_NOATIME'] = 262144;
	$pyjs['track']['lineno']=41;
	$m['O_NOCTTY'] = 256;
	$pyjs['track']['lineno']=42;
	$m['O_NOFOLLOW'] = 131072;
	$pyjs['track']['lineno']=43;
	$m['O_NONBLOCK'] = 2048;
	$pyjs['track']['lineno']=44;
	$m['O_RDONLY'] = 0;
	$pyjs['track']['lineno']=45;
	$m['O_RDWR'] = 2;
	$pyjs['track']['lineno']=46;
	$m['O_RSYNC'] = 1052672;
	$pyjs['track']['lineno']=47;
	$m['O_SYNC'] = 1052672;
	$pyjs['track']['lineno']=48;
	$m['O_TRUNC'] = 512;
	$pyjs['track']['lineno']=49;
	$m['O_WRONLY'] = 1;
	$pyjs['track']['lineno']=50;
	$m['R_OK'] = 4;
	$pyjs['track']['lineno']=51;
	$m['TMP_MAX'] = 238328;
	$pyjs['track']['lineno']=52;
	$m['WCONTINUED'] = 8;
	$pyjs['track']['lineno']=53;
	$m['WNOHANG'] = 1;
	$pyjs['track']['lineno']=54;
	$m['WUNTRACED'] = 2;
	$pyjs['track']['lineno']=55;
	$m['W_OK'] = 2;
	$pyjs['track']['lineno']=56;
	$m['X_OK'] = 1;
	$pyjs['track']['lineno']=58;
	$m['environ'] = (function(){try{try{$pyjs['in_try_except'] += 1;
	return $p['dict']([]);
}finally{$pyjs['in_try_except']-=1;}}catch($pyjs_dbg_1_err){if (!$p['isinstance']($pyjs_dbg_1_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_1_err);}throw $pyjs_dbg_1_err;
}})();
	$pyjs['track']['lineno']=60;
	$m['urandom'] = function(n) {

		$pyjs['track']={'module':'os','lineno':60};$pyjs['trackstack']['push']($pyjs['track']);
		$pyjs['track']['module']='os';
		$pyjs['track']['lineno']=60;
		$pyjs['track']['lineno']=74;
		$pyjs['__active_exception_stack__'] = null;
		throw ((function(){try{try{$pyjs['in_try_except'] += 1;
		return $p['NotImplementedError']('/dev/urandom (or equivalent) not found');
}finally{$pyjs['in_try_except']-=1;}}catch($pyjs_dbg_2_err){if (!$p['isinstance']($pyjs_dbg_2_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_2_err);}throw $pyjs_dbg_2_err;
}})());
		$pyjs['track']['lineno']=75;
		$pyjs['track']['lineno']=75;
		var $pyjs__ret = (typeof bs == "undefined"?$m['bs']:bs);
		$pyjs['trackstack']['pop']();$pyjs['track']=$pyjs['trackstack']['pop']();$pyjs['trackstack']['push']($pyjs['track']);
		return $pyjs__ret;
	};
	$m['urandom']['__name__'] = 'urandom';

	$m['urandom']['__bind_type__'] = 0;
	$m['urandom']['__args__'] = [null,null,['n']];
	$pyjs['track']['lineno']=77;
	$m['unlink'] = function() {
		var args = $p['tuple']($pyjs_array_slice['call'](arguments,0,arguments['length']));


		$pyjs['track']={'module':'os','lineno':77};$pyjs['trackstack']['push']($pyjs['track']);
		$pyjs['track']['module']='os';
		$pyjs['track']['lineno']=77;
		$pyjs['track']['lineno']=78;
		$pyjs['__active_exception_stack__'] = null;
		throw ((function(){try{try{$pyjs['in_try_except'] += 1;
		return $p['NotImplementedError']('PyJS does not support filesystem access');
}finally{$pyjs['in_try_except']-=1;}}catch($pyjs_dbg_3_err){if (!$p['isinstance']($pyjs_dbg_3_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_3_err);}throw $pyjs_dbg_3_err;
}})());
		$pyjs['trackstack']['pop']();$pyjs['track']=$pyjs['trackstack']['pop']();$pyjs['trackstack']['push']($pyjs['track']);
		return null;
	};
	$m['unlink']['__name__'] = 'unlink';

	$m['unlink']['__bind_type__'] = 0;
	$m['unlink']['__args__'] = ['args',null];
	return this;
}; /* end os */


/* end module: os */


/*
PYJS_DEPS: ['path', 'os.path.walk', 'os', 'os.path', 'os.path.curdir', 'os.path.pardir', 'os.path.sep', 'os.path.pathsep', 'os.path.defpath', 'os.path.extsep', 'os.path.altsep', 'os.path.devnull']
*/
